apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  username: admin
  password: MonMotDePasseSecret123
  connection-string: postgresql://admin:MonMotDePasseSecret123@db-service:5432/mydb
